# Generated by Django 4.1.13 on 2025-05-17 17:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommstore', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cutomer',
            new_name='Customer',
        ),
    ]
