# Generated by Django 4.1.13 on 2025-05-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommstore', '0003_rename_cutomer_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ecommstore/static'),
        ),
    ]
