# Generated by Django 4.1.13 on 2025-05-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommstore', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='termsnconditions',
            field=models.TextField(null=True),
        ),
    ]
