# Generated by Django 4.1.13 on 2025-05-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommstore', '0006_product_specification_product_termsnconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.JSONField(null=True),
        ),
    ]
