# Generated by Django 4.1.13 on 2025-05-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommstore', '0007_alter_product_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='termsnconditions',
            field=models.JSONField(null=True),
        ),
    ]
