# Generated by Django 4.1.13 on 2025-05-22 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommstore', '0008_alter_product_termsnconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommstore.product')),
            ],
        ),
    ]
