# Generated by Django 4.1.13 on 2025-05-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommstore', '0011_alter_product_desc1_productvariant_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
