# Generated by Django 4.1.13 on 2025-06-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommstore', '0013_userprofile_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('placed', 'placed'), ('shipped', 'shipped'), ('delivered', 'delivered')], default='created', max_length=15),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unitprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
