# Generated by Django 4.1.13 on 2025-06-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommstore', '0014_order_amount_order_status_orderitem_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
