# Generated by Django 4.1.13 on 2025-06-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommstore', '0015_cartitem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='related_order',
            field=models.CharField(default='NA', max_length=12),
            preserve_default=False,
        ),
    ]
